apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: myoperators.foperator.test
spec:
  group: foperator.test  # 自定义资源所属组
  version: v1alpha1      # 自定义资源版本
  names:
    kind: MyOperator     # 自定义资源对象的类型
    plural: myoperators  # 自定义资源对象的复数形式
  scope: Namespaced      # 自定义资源的作用域，此处为在命名空间内