apiVersion: foperator.test/v1alpha1
kind: MyOperator
metadata:
  labels:
    mylable: mycontroller
  name: example-operator
  namespace: fns
spec:
  command: "test command"
  items:
    - name: "item1"
      value: "11111111111"
    - name: "item2"
      value: "22222222222"